# Generated by Django 3.1.7 on 2021-04-19 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20210319_0313'),
        ('vendor', '0005_auto_20210322_0910'),
        ('riskassessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptinfo',
            name='mpc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.userdepartment', verbose_name='Main Project Contact'),
        ),
        migrations.AddField(
            model_name='vendinfo',
            name='mpc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendor.uservendor', verbose_name='Main Project Contact'),
        ),
        migrations.AlterField(
            model_name='datamanagement',
            name='data_classi',
            field=models.CharField(choices=[('Highly Sensitive', 'Highly Sensitive'), ('Sensitive', 'Sensitive'), ('Internal', 'Internal'), ('Public', 'Public')], max_length=16, verbose_name='Data Classification'),
        ),
        migrations.AlterField(
            model_name='datamanagement',
            name='data_rcvd_outside',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is any data received (directly or indirectly by Company) from individuals outside of the US?'),
        ),
        migrations.AlterField(
            model_name='datamanagement',
            name='reg_data',
            field=models.CharField(choices=[('FERPA', 'FERPA'), ('HIPAA', 'HIPAA'), ('GDPR', 'GDPR'), ('ITAR', 'ITAR'), ('PCI', 'PCI'), ('PII', 'PII')], max_length=5, verbose_name='Regulated Data'),
        ),
    ]
