# Generated by Django 3.1.7 on 2021-04-19 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0003_riskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Added'),
            preserve_default=False,
        ),
    ]
