# Generated by Django 3.1.7 on 2021-04-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0004_riskassessment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabiltycriticality',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cloudservice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='product',
        ),
        migrations.RemoveField(
            model_name='databaseservers',
            name='product',
        ),
        migrations.RemoveField(
            model_name='datamanagement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='deptinfo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='encryption',
            name='product',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='product',
        ),
        migrations.RemoveField(
            model_name='qaenvironment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='secmatevidence',
            name='product',
        ),
        migrations.RemoveField(
            model_name='securecomms',
            name='product',
        ),
        migrations.RemoveField(
            model_name='securedesign',
            name='product',
        ),
        migrations.RemoveField(
            model_name='swintegrity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vendinfo',
            name='product',
        ),
        migrations.AddField(
            model_name='availabiltycriticality',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabiltycriticality',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='cloudservice',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudservice',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliance',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='databaseservers',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databaseservers',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='deptinfo',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deptinfo',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='encryption',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encryption',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='integration',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='qaenvironment',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qaenvironment',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='secmatevidence',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secmatevidence',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='securecomms',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securecomms',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='securedesign',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securedesign',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='swintegrity',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swintegrity',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='vendinfo',
            name='riskassessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendinfo',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
    ]
