# Generated by Django 3.1.7 on 2021-04-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0005_auto_20210420_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeptInfo',
        ),
    ]
