# Generated by Django 3.1.7 on 2021-04-20 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20210319_0313'),
        ('riskassessment', '0006_delete_deptinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_name', models.CharField(max_length=100, verbose_name='Name')),
                ('ta_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('ta_phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('eur_name', models.CharField(max_length=100, verbose_name='Name')),
                ('eur_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('eur_phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('ds_name', models.CharField(max_length=100, verbose_name='Name')),
                ('ds_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('ds_phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('vend_has_perm', models.BooleanField(default=False, verbose_name='Vendor can edit?')),
                ('score', models.IntegerField(default=0, verbose_name='Section Score')),
                ('mpc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.userdepartment', verbose_name='Main Project Contact')),
                ('riskassessment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riskassessment.riskassessment', verbose_name='Risk Assessment')),
            ],
            options={
                'verbose_name': 'Department Information',
                'verbose_name_plural': 'Department Information',
            },
        ),
    ]
