# Generated by Django 3.1.7 on 2021-04-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0007_deptinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Sensitivity')),
            ],
            options={
                'verbose_name': 'Data Classification',
                'verbose_name_plural': 'Data Classification',
            },
        ),
        migrations.CreateModel(
            name='RegulatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='Data Type')),
            ],
            options={
                'verbose_name': 'Regulated Data',
                'verbose_name_plural': 'Regulated Data',
            },
        ),
    ]
