# Generated by Django 3.1.7 on 2021-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0008_dataclassification_regulateddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamanagement',
            name='data_classi',
            field=models.CharField(choices=[('Highly Sensitive', 'Highly Sensitive'), ('Sensitive', 'Sensitive'), ('Internal', 'Internal'), ('Public', 'Public')], max_length=55, verbose_name='Data Classification'),
        ),
        migrations.AlterField(
            model_name='datamanagement',
            name='reg_data',
            field=models.CharField(choices=[('FERPA', 'FERPA'), ('HIPAA', 'HIPAA'), ('GDPR', 'GDPR'), ('ITAR', 'ITAR'), ('PCI', 'PCI'), ('PII', 'PII')], max_length=50, verbose_name='Regulated Data'),
        ),
    ]
