# Generated by Django 3.1.7 on 2021-04-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0009_auto_20210420_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamanagement',
            name='data_classi',
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='data_classi',
            field=models.ManyToManyField(to='riskassessment.DataClassification', verbose_name='Data Classification'),
        ),
        migrations.RemoveField(
            model_name='datamanagement',
            name='reg_data',
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='reg_data',
            field=models.ManyToManyField(to='riskassessment.RegulatedData', verbose_name='Regulated Data'),
        ),
    ]
