# Generated by Django 3.1.7 on 2021-04-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0010_auto_20210420_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamanagement',
            name='est_add_recs',
            field=models.IntegerField(choices=[(500, 500), (1000, 1000), (2000, 2000), (3000, 3000), (4000, 4000), (5000, 5000), (6000, 6000), (7000, 7000)], verbose_name='Estimated yearly additional records'),
        ),
        migrations.AlterField(
            model_name='datamanagement',
            name='recs_in_data',
            field=models.IntegerField(choices=[(500, 500), (1000, 1000), (2000, 2000), (3000, 3000), (4000, 4000), (5000, 5000), (6000, 6000), (7000, 7000)], verbose_name='Number of Records in Data'),
        ),
    ]
