# Generated by Django 3.1.7 on 2021-04-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0011_auto_20210420_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='steps_complete',
            field=models.IntegerField(default=0, verbose_name='Steps Completed'),
        ),
    ]
