# Generated by Django 3.1.7 on 2021-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0012_riskassessment_steps_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptinfo',
            name='vend_has_perm',
        ),
        migrations.AddField(
            model_name='availabiltycriticality',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='cloudservice',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='databaseservers',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='deptinfo',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='encryption',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='integration',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='qaenvironment',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='secmatevidence',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='securecomms',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='securedesign',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='swintegrity',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
    ]
