# Generated by Django 3.1.7 on 2021-04-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20210319_0313'),
        ('riskassessment', '0014_auto_20210421_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptinfo',
            name='ds_dept',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ds_dept', to='department.department', verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deptinfo',
            name='eur_dept',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eur_dept', to='department.department', verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deptinfo',
            name='ta_dept',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ta_dept', to='department.department', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
