# Generated by Django 3.1.7 on 2021-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0015_auto_20210421_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved?'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='evaluated',
            field=models.BooleanField(default=False, verbose_name='Evaluated?'),
        ),
    ]
