# Generated by Django 3.1.7 on 2021-04-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0016_auto_20210421_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabiltycriticality',
            name='max_score',
            field=models.IntegerField(default=10, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='cloudservice',
            name='max_score',
            field=models.IntegerField(default=3, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='max_score',
            field=models.IntegerField(default=9, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='databaseservers',
            name='max_score',
            field=models.IntegerField(default=13, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='max_score',
            field=models.IntegerField(default=15, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='deptinfo',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='encryption',
            name='max_score',
            field=models.IntegerField(default=41, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='integration',
            name='max_score',
            field=models.IntegerField(default=9, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='qaenvironment',
            name='max_score',
            field=models.IntegerField(default=12, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='secmatevidence',
            name='max_score',
            field=models.IntegerField(default=12, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='securecomms',
            name='max_score',
            field=models.IntegerField(default=20, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='securedesign',
            name='max_score',
            field=models.IntegerField(default=19, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='swintegrity',
            name='max_score',
            field=models.IntegerField(default=12, verbose_name='Section Score'),
        ),
        migrations.AddField(
            model_name='vendinfo',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='Section Score'),
        ),
    ]
