# Generated by Django 3.1.7 on 2021-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0017_auto_20210421_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptinfo',
            name='eval_score',
            field=models.IntegerField(default=0, verbose_name='Evaluated Score'),
        ),
        migrations.AddField(
            model_name='vendinfo',
            name='eval_score',
            field=models.IntegerField(default=0, verbose_name='Evaluated Score'),
        ),
    ]
