# Generated by Django 3.1.7 on 2021-04-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0019_auto_20210421_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptinfo',
            name='eval_max_score',
        ),
        migrations.RemoveField(
            model_name='vendinfo',
            name='eval_max_score',
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='eval_score',
            field=models.IntegerField(default=0, verbose_name='Maxed Score'),
        ),
        migrations.AlterField(
            model_name='vendinfo',
            name='eval_score',
            field=models.IntegerField(default=0, verbose_name='Maxed Score'),
        ),
    ]
