# Generated by Django 3.1.7 on 2021-04-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0021_riskassessment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabiltycriticality',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step4', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='cloudservice',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step8', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step5', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='databaseservers',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step12', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='datamanagement',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step3', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step1', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step10', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step7', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='qaenvironment',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step11', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='secmatevidence',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step6', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='securecomms',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step13', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='securedesign',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step9', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='swintegrity',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step14', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='vendinfo',
            name='riskassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_step2', to='riskassessment.riskassessment', verbose_name='Risk Assessment'),
        ),
    ]
