# Generated by Django 3.1.7 on 2021-04-29 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riskassessment', '0024_riskassessment_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='ra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', verbose_name='Risk Analyst'),
        ),
    ]
