# Generated by Django 3.1.7 on 2021-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0025_auto_20210429_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='ra_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='RA Number'),
        ),
    ]
