# Generated by Django 3.1.7 on 2021-04-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0026_riskassessment_ra_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendinfo',
            name='mpc_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Vendor Primary Contact Email'),
        ),
        migrations.AddField(
            model_name='vendinfo',
            name='mpc_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Primary Contact Name'),
        ),
        migrations.AddField(
            model_name='vendinfo',
            name='mpc_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Vendor Primary Contact Phone'),
        ),
        migrations.AlterField(
            model_name='vendinfo',
            name='exst_contract',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Negotiation', 'Under Negotiation')], max_length=18, verbose_name='Master Agreement?'),
        ),
        migrations.AlterField(
            model_name='vendinfo',
            name='tc_email',
            field=models.EmailField(max_length=100, verbose_name='Technical Contact Email'),
        ),
        migrations.AlterField(
            model_name='vendinfo',
            name='tc_name',
            field=models.CharField(max_length=100, verbose_name='Technical Contact Name'),
        ),
        migrations.AlterField(
            model_name='vendinfo',
            name='tc_phone',
            field=models.CharField(max_length=10, verbose_name='Technical Contact Phone'),
        ),
    ]
