# Generated by Django 3.1.7 on 2021-04-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0027_auto_20210429_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendinfo',
            name='mpc_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Vendor Primary Contact Email'),
        ),
        migrations.AlterField(
            model_name='vendinfo',
            name='mpc_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vendor Primary Contact Name'),
        ),
        migrations.AlterField(
            model_name='vendinfo',
            name='mpc_phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Vendor Primary Contact Phone'),
        ),
    ]
