# Generated by Django 3.1.7 on 2021-04-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskassessment', '0028_auto_20210429_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendinfo',
            name='mpc',
        ),
    ]
