from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(RiskAssessment)
admin.site.register(DeptInfo)
admin.site.register(VendInfo)
admin.site.register(DataManagement)
admin.site.register(AvailabiltyCriticality)
admin.site.register(Compliance)
admin.site.register(SecMatEvidence)
admin.site.register(Integration)
admin.site.register(CloudService)
admin.site.register(SecureDesign)
admin.site.register(Encryption)
admin.site.register(QAEnvironment)
admin.site.register(DatabaseServers)
admin.site.register(SecureComms)
admin.site.register(SWIntegrity)
admin.site.register(DataClassification)
admin.site.register(RegulatedData)