# Generated by Django 3.1.7 on 2021-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_userdepartment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_uservendor',
            field=models.BooleanField(default=False),
        ),
    ]
