# Generated by Django 3.1.7 on 2021-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210317_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
