# Generated by Django 3.1.7 on 2021-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_userdepartment',
            field=models.BooleanField(default=False, verbose_name='Is Department User'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_uservendor',
            field=models.BooleanField(default=False, verbose_name='Is Vendor User'),
        ),
    ]
