# Generated by Django 3.1.7 on 2021-03-19 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_userdepartment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdepartment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AlterField(
            model_name='userdepartment',
            name='userType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.usertypedepartment'),
        ),
    ]
