# Generated by Django 3.1.7 on 2021-03-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20210319_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdepartment',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.usertypedepartment'),
        ),
    ]
